export const strings = {
  c: "C•",
  clothify: "Clothify",
  clothifyTitle: "The Clothify App That Makes You Look Your Best",
  clothifyDescription:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
  getStarted: "Let's Get Started",
  alreadyAccount: "Already have an account?  ",
  signIn: "Sign In",
  OnboardingLoremText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
  GetStarted:  "Let's Get Started!",
  NewFeatures: "Discover New Features",
  SeamlessExp: "Seamless Shopping Experiences",
  Hiwelcometextmissed: "Hi! Welcome back, you've been missed",
  fillinformationregisterText: "Fill your information below or register with your social account",
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot Password?",
  orSignInWith: "Or sign in with",
  orSignUpWith: "Or sign up with",
  dontHaveAccount: "Don't have an account? ",
  alreadyhaveAccount: "Already have an account? ",
  signUp: "Sign Up",
  name: "Name",
  agreewith: "Agree with",
  termscondition: "Terms & Conditions",
  tick: "✓",
  createAccount: "Create Account",
  verify: "Verify",
  enterthecode: "Please enter the code we just sent to email",
  emailTextdemo: "example@gmail.com",
  didntreceiveotp: "Didnt't recieve OTP?",
  resendCode: "Resend Code",
  GetStartedOnly: "Get Started",
  newPassword: "New Password",
  passwordInfo: "Your new password must be different from previously used passwords.",
  confirmPassword: "Confirm Password",
  passwordPlaceholder: "********",
  createNewPassword: "Create New Password",
  passwordError: "Password must be at least 8 characters, with a number & special character.",
  confirmPasswordError: "Passwords do not match.",
  enternewpass: "Enter your new password to continue.",
  completeyourprofile: "Complete Your Profile",
  dataprofileInfo: "Don't worry, only you can see your personal data, No one else will be able to see it",
  phonenumber: "Phone Number",
  entervalidemail: "Enter a valid email",
  Passrequired: "Password is required",
  passwordlength: "Password must be at least 8 characters",
  namerequired: "Name is required",
  namelength: "Name must be at least 2 characters",
  emailrequired: "Email is required",
  johndoe: "John Doe",
  whatslocation: "What is your Location?",
  locationinfotext: "We need to know your location in order to suggest nearby services",
  allowlocationaccess: "Allow Location Access",
  manualLocationtext: "Enter Location Manually",
  enteryourlocation: "Enter Your Location",
  searchLocation: "Search location",
  usecurrentlocation: "Use my current location",
  searchresult: "SEARCH RESULT",
  goldnavnue: "Golden Avenue",
  prestonRd: "8502 Preston Rd. Ingl..",
  permissionDenied: "Permission Denied",
  locationaccessneeded: "Location access is required to continue.",
  locationlog: "Location:",
  locationaccessed: "Location Accessed",
  tshirt: "T-Shirt",
  Shirt: "Shirt",
  pant: "Pant",
  Dress: "Dress",
  Jacket: "Jacket",
  brownjacket: "Brown Jacket",
  brownsuit: "Brown Suit",
  yelloshirt: "Yellow Shirt",
  price1: "$83.97",
  price2: "$120.00",
  price3: "$90.97",
  price4: "$150.00",
  newcollection: "New Collection",
  discounttext: "Discount 50% for the first transaction",
  shopnow: "Shop Now",
  category: "Category",
  seeAll: "See All",
  Home: "Home",
  Bag: "Cart",
  Whistlist: "Whistlist",
  Message: "Message",
  UserProfile: "Profile",
  flashsale: "Flash Sale",
  ClosingIn: "Closing in:",
  All: "All",
  Newest: "Newest",
  Popular: "Popular",
  Man: "Man",
  Women: "Women",
  Kids: "Kids",
  location: "Location",
  productdetailheading: "Product Details",
  femalestyletext: "Female's Style",
  rating45: "4.5",
  lightbrownjacket: "Light Brown Jacket",
  loremtext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua",
  readmore: " Read more",
  selectsize: "Select Size",
  S: "S",
  M: "M",
  L: "L",
  XL: "XL",
  XXL: "XXL",
  XXXL: "XXXL",
  selectColor: "Select Color:",
  none: "None",
  totalprice: "Total Price",
  pricejacket: "$83.97",
  addtocart: "Add to Cart",
  mywhistlist: "My Whistlist",
  brownshirt: "Brown Shirt",
  jacketchoco: "jacket chocolate",
  mycart: "My Cart",
  size: "Size :",
  minus: "-",
  plus:"+",
  freeforall: "FREEFORALL",
  first100: "FIRST100",
  happynew500: "HAPPYNEW500",
  invalidnewpromocode: "Invalid Promo Code",
  apply: "Apply",
  subtotal: "Sub-Total:",
  deliveryfee: "Delivery Fee:",
  discount: "Discount:",
  totalcost: "Total Cost:",
  proceedtocheckout: "Proceed to Checkout",
  yourcartempty: "Your cart is empty",
  checkout: "Checkout",
  shippingaddress: "Shipping Address",
  address1: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
  address2: "4517 Washington Ave. Manchester, Kentucky 39495",
  address3: "8502 Preston Rd. Inglewood, Maine 98380",
  address4: "2464 Royal Ln. Mesa, New Jersey 45463",
  Change: "CHANGE",
  chooseshippingtype: "Choose Shipping Type",
  economy: "Economy",
  estimatedarrivaltext: "Estimated Arrival 25 August 2023",
  orderlist: "Order List",
  continuepayment: "Continue to Payment",
  office: "Office",
  parentshouse: "Parent's House",
  friendshouse: "Friend's House",
  addnewaddress: "Add New Shipping Address",
  chooseshipping: "Choose Shipping",
  regular: "Regular",
  cargo: "Cargo",
  estimatedarrivaltext1: "Estimated Arrival 24 August 2023",
  estimatedarrivaltext2: "Estimated Arrival 22 August 2023",
  estimatedarrivaltext3: "Estimated Arrival 20 August 2023",
  paymentmethod: "Payment Method",
  creditdebitcard: "Credit & Debit Card",
  addcard: "Add Card",
  morepaymentoptions: "More Payment Options",
  paypal: "Paypal",
  applepay: "Apple Pay",
  googlepay: "Google Pay",
  confirmpayment: "Confirm Payment",
  payment: "Payment",
  vieworder: "View Order",
  viewereceipt: "View E Receipt",
}
export const localizedStrings = {
    text: "text",
    placeholderColor: "placeholderColor",
    dark: "dark",
    light: "dark",
    black: "black",
    white: "white",
    auto: "auto",
  }