export const strings = {
  c: "C•",
  clothify: "Clothify",
  clothifyTitle: "The Clothify App That Makes You Look Your Best",
  clothifyDescription:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
  getStarted: "Let's Get Started",
  alreadyAccount: "Already have an account?  ",
  signIn: "Sign In",
  OnboardingLoremText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
  GetStarted:  "Let's Get Started!",
  NewFeatures: "Discover New Features",
  SeamlessExp: "Seamless Shopping Experiences",
  Hiwelcometextmissed: "Hi! Welcome back, you've been missed",
  fillinformationregisterText: "Fill your information below or register with your social account",
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot Password?",
  orSignInWith: "Or sign in with",
  orSignUpWith: "Or sign up with",
  dontHaveAccount: "Don't have an account? ",
  alreadyhaveAccount: "Already have an account? ",
  signUp: "Sign Up",
  name: "Name",
  agreewith: "Agree with",
  termscondition: "Terms & Conditions",
  tick: "✓",
  createAccount: "Create Account",
  verify: "Verify",
  enterthecode: "Please enter the code we just sent to email",
  emailTextdemo: "example@gmail.com",
  didntreceiveotp: "Didnt't recieve OTP?",
  resendCode: "Resend Code",
  GetStartedOnly: "Get Started",
  newPassword: "New Password",
  passwordInfo: "Your new password must be different from previously used passwords.",
  confirmPassword: "Confirm Password",
  passwordPlaceholder: "********",
  createNewPassword: "Create New Password",
  passwordError: "Password must be at least 8 characters, with a number & special character.",
  confirmPasswordError: "Passwords do not match.",
  enternewpass: "Enter your new password to continue.",
  completeyourprofile: "Complete Your Profile",
  dataprofileInfo: "Don't worry, only you can see your personal data, No one else will be able to see it",
  phonenumber: "Phone Number",
  entervalidemail: "Enter a valid email",
  Passrequired: "Password is required",
  passwordlength: "Password must be at least 8 characters",
  namerequired: "Name is required",
  namelength: "Name must be at least 2 characters",
  emailrequired: "Email is required",
  johndoe: "John Doe",
  whatslocation: "What is your Location?",
  locationinfotext: "We need to know your location in order to suggest nearby services",
  allowlocationaccess: "Allow Location Access",
  manualLocationtext: "Enter Location Manually",
  enteryourlocation: "Enter Your Location",
  searchLocation: "Search location",
  usecurrentlocation: "Use my current location",
  searchresult: "SEARCH RESULT",
  goldnavnue: "Golden Avenue",
  prestonRd: "8502 Preston Rd. Ingl..",
  permissionDenied: "Permission Denied",
  locationaccessneeded: "Location access is required to continue.",
  locationlog: "Location:",
  locationaccessed: "Location Accessed",
}
export const localizedStrings = {
    text: "text",
    placeholderColor: "placeholderColor",
    dark: "dark",
    light: "dark",
    black: "black",
    white: "white",
    auto: "auto",
  }