export const strings = {
  c: "C•",
  clothify: "Clothify",
  clothifyTitle: "The Clothify App That Makes You Look Your Best",
  clothifyDescription:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
  getStarted: "Let's Get Started",
  alreadyAccount: "Already have an account?  ",
  signIn: "Sign In",
  OnboardingLoremText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
  GetStarted:  "Let's Get Started!",
  NewFeatures: "Discover New Features",
  SeamlessExp: "Seamless Shopping Experiences",
  Hiwelcometextmissed: "Hi! Welcome back, you've been missed",
  fillinformationregisterText: "Fill your information below or register with your social account",
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot Password?",
  orSignInWith: "Or sign in with",
  orSignUpWith: "Or sign up with",
  dontHaveAccount: "Don't have an account? ",
  alreadyhaveAccount: "Already have an account? ",
  signUp: "Sign Up",
  name: "Name",
  agreewith: "Agree with",
  termscondition: "Terms & Conditions",
  tick: "✓",
  cross: "✕",
  createAccount: "Create Account",
  verify: "Verify",
  enterthecode: "Please enter the code we just sent to email",
  emailTextdemo: "example@gmail.com",
  didntreceiveotp: "Didnt't recieve OTP?",
  resendCode: "Resend Code",
  GetStartedOnly: "Get Started",
  newPassword: "New Password",
  passwordInfo: "Your new password must be different from previously used passwords.",
  confirmPassword: "Confirm Password",
  passwordPlaceholder: "********",
  createNewPassword: "Create New Password",
  passwordError: "Password must be at least 8 characters, with a number & special character.",
  confirmPasswordError: "Passwords do not match.",
  enternewpass: "Enter your new password to continue.",
  completeyourprofile: "Complete Your Profile",
  dataprofileInfo: "Don't worry, only you can see your personal data, No one else will be able to see it",
  phonenumber: "Phone Number",
  entervalidemail: "Enter a valid email",
  Passrequired: "Password is required",
  passwordlength: "Password must be at least 8 characters",
  namerequired: "Name is required",
  namelength: "Name must be at least 2 characters",
  emailrequired: "Email is required",
  johndoe: "John Doe",
  whatslocation: "What is your Location?",
  locationinfotext: "We need to know your location in order to suggest nearby services",
  allowlocationaccess: "Allow Location Access",
  manualLocationtext: "Enter Location Manually",
  enteryourlocation: "Enter Your Location",
  searchLocation: "Search location",
  usecurrentlocation: "Use my current location",
  searchresult: "SEARCH RESULT",
  goldnavnue: "Golden Avenue",
  prestonRd: "8502 Preston Rd. Ingl..",
  permissionDenied: "Permission Denied",
  locationaccessneeded: "Location access is required to continue.",
  locationlog: "Location:",
  locationaccessed: "Location Accessed",
  tshirt: "T-Shirt",
  Shirt: "Shirt",
  pant: "Pant",
  Dress: "Dress",
  Jacket: "Jacket",
  brownjacket: "Brown Jacket",
  brownsuit: "Brown Suit",
  yelloshirt: "Yellow Shirt",
  price1: "$83.97",
  price2: "$120.00",
  price3: "$90.97",
  price4: "$150.00",
  newcollection: "New Collection",
  discounttext: "Discount 50% for the first transaction",
  shopnow: "Shop Now",
  category: "Category",
  seeAll: "See All",
  Home: "Home",
  Bag: "Cart",
  Whistlist: "Whistlist",
  Message: "Message",
  UserProfile: "Profile",
  flashsale: "Flash Sale",
  ClosingIn: "Closing in:",
  All: "All",
  Newest: "Newest",
  Popular: "Popular",
  Man: "Man",
  Men: "Men",
  Women: "Women",
  Kids: "Kids",
  location: "Location",
  productdetailheading: "Product Details",
  femalestyletext: "Female's Style",
  rating45: "4.5",
  lightbrownjacket: "Light Brown Jacket",
  loremtext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua",
  readmore: " Read more",
  selectsize: "Select Size",
  S: "S",
  M: "M",
  L: "L",
  XL: "XL",
  XXL: "XXL",
  XXXL: "XXXL",
  selectColor: "Select Color:",
  none: "None",
  totalprice: "Total Price",
  pricejacket: "$83.97",
  addtocart: "Add to Cart",
  mywhistlist: "My Whistlist",
  brownshirt: "Brown Shirt",
  jacketchoco: "jacket chocolate",
  mycart: "My Cart",
  size: "Size :",
  minus: "-",
  plus:"+",
  freeforall: "FREEFORALL",
  first100: "FIRST100",
  happynew500: "HAPPYNEW500",
  welcome200: "WELCOME200",
  cashback12: "CASHBACK12",
  fest2cost: "FEST2COST",
  invalidnewpromocode: "Invalid Promo Code",
  apply: "Apply",
  subtotal: "Sub-Total:",
  deliveryfee: "Delivery Fee:",
  discount: "Discount:",
  totalcost: "Total Cost:",
  proceedtocheckout: "Proceed to Checkout",
  yourcartempty: "Your cart is empty",
  checkout: "Checkout",
  shippingaddress: "Shipping Address",
  address1: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
  address2: "4517 Washington Ave. Manchester, Kentucky 39495",
  address3: "8502 Preston Rd. Inglewood, Maine 98380",
  address4: "2464 Royal Ln. Mesa, New Jersey 45463",
  Change: "CHANGE",
  chooseshippingtype: "Choose Shipping Type",
  economy: "Economy",
  estimatedarrivaltext: "Estimated Arrival 25 August 2023",
  orderlist: "Order List",
  continuepayment: "Continue to Payment",
  office: "Office",
  parentshouse: "Parent's House",
  friendshouse: "Friend's House",
  addnewaddress: "Add New Shipping Address",
  chooseshipping: "Choose Shipping",
  regular: "Regular",
  cargo: "Cargo",
  estimatedarrivaltext1: "Estimated Arrival 24 August 2023",
  estimatedarrivaltext2: "Estimated Arrival 22 August 2023",
  estimatedarrivaltext3: "Estimated Arrival 20 August 2023",
  paymentmethod: "Payment Method",
  creditdebitcard: "Credit & Debit Card",
  addcard: "Add Card",
  morepaymentoptions: "More Payment Options",
  paypal: "Paypal",
  applepay: "Apple Pay",
  googlepay: "Google Pay",
  confirmpayment: "Confirm Payment",
  payment: "Payment",
  vieworder: "View Order",
  viewereceipt: "View E Receipt",
  coupon: "Coupon",
  additemsworth: "Add items worth",
  moretounlock: "more to unlock",
  GET: "Get",
  copycode: "COPY CODE",
  bestoffersText: "Best Offers for you",
  dollar2: "$2",
  dollar28: "$28",
  dollar10: "$10",
  dollar350: "$350",
  dollar0: "$0",
  visa: "Visa",
  mastercard: "MasterCard",
  americanexpress: "American Express",
  discover: "Discover",
  cardType: "Card Type",
  estherhoward: "Esther Howard",
  cardholdername: "Card holder name",
  expirydate: "Expiry date",
  expire0230: "02/30",
  CARDHOLDERNAME: "Card Holder Name",
  cardnumber: "Card Number",
  placeholdercardnumber: "4716 9627 1635 8047",
  expireDate: "Expiry Date",
  cvv: "CVV",
  three0: "000",
  savecard: "Save Card",
  promocode: "Promo Code",
  haveavalidcoupon: "Have a valid Coupons ? / Apply Promo Code",
  seeallcoupons: "See All Coupons",
  removefromcart: "Remove from Cart?",
  cancel: "Cancel",
  yesremove: "Yes, Remove",
  enterphonenumber: "Enter Phone Number",
  gender: "Gender",
  select: "Select",
  completeprofile: "Complete Profile",
  search: "Search",
  newyork: "New York, USA",
  losangeles: "Los Angeles, USA",
  london: "London, UK",
  berlin: "Berlin, Germany",
  tokyo: "Tokyo, Japan",
  sydney: "Sydney, Australia",
  toronto: "Toronto, Canada",
  mumbai: "Mumbai, India",
  paris: "Paris, France",
  dubai: "Dubai, UAE",
  granted: "granted",
  permissiondenied: "Permission Denied", 
  locationacessrequired: "Location access is required.",
  unknownlocation: "Unknown Location",
  passwordcharacter: "Password must be at least 8 characters, with a number & special character.",
  passwordchangedsuccess: "Password changed successfully!",
  paymentsuccess: "Payment Successful",
  thankyoupurchase: "Thank you for your purchase",
  failedloadcards: "Failed to load saved cards",
  errorsavingcard: "Error saving card:",
  cvvv: "CVV:",
  expiry: "Expiry:",
  holder: "Holder:",
  nosavecards: "No saved cards",
  PAYPAL: "paypal",
  APPLEPAY: "applepay",
  GOOGLEPAY: "googlepay",
  starText: "************",
  otpentered: "OTP Entered:",
  jem: ":",
  paste: "Paste",
  Recents: "Recents",
  ClearAll: "Clear All",
  filter: "Filter",
  Nike: "Nike",
  Puma: "Puma",
  Adidas: "Adidas",
  Jordans: "Jordans",
  Reebok: "Reedbok",
  Brands: "Brands",
  sortby: "Sort By",
  trending: "Trending",
  pricelow: "Price Low",
  pricehigh: "Price High",
  mostrecent: "Most Recent",
  pricerange: "Price Range",
  reviews: "Reviews",
  star1: "4.5 and above",
  star2: "4.0 - 4.5",
  star3: "3.5 - 4.0",
  star4: "3.0 - 3.5",
  star5: "2.5 - 3.0",
  star6: "2.0 - 2.5",
  star7: "1.5 - 2.0",
  star8: "1.0 - 1.5",
  resetfilter: "Reset Filter",
  myorders: "My Orders",
  active: "Active",
  completed: "Completed",
  cancelled: "Cancelled",
  trackorder: "Track Order",
  leavereview: "Leave Review",
  reorder: "Re-Order",
  darkbrownjacket: "Dark Brown Jacket",
  blackblazer: "Black Blazer",
  redshirt: "Red Shirt",
  QTY: "| Qty :",
  $: "$",
  pcs1: "1 pc",
  pcs2: "2 pcs",
  pcs3: "3 pcs",
  pcs4: "4 pcs",
  lightgreyjacket: "Light Grey Jacket",
  orangeshirt: "Orange Shirt",
  blacksuit: "Black Suit", 
  maroonsweatshirt: "Maroon Sweatshirt",
  sweatshirt: "Sweatshirt",
  creamyshirt: "Creamy Shirt",
  whitevanillashirt: "White Vanilla Shirt",
  whitecreamyshirt: "White Creamy Shirt",
  slimbrownsweater: "Slim Brown Sweater",
  whitefrock: "White Frock",
  lightgreencoat: "Light Green Coat",
  darkwoodshirt: "Dark Wood Shirt",
  brownishTreeDress: "Brownish Tree Dress",
  whitewoodBlazer: "White Wood Blazer",
  LeaveReview: "Leave Review",
  howsyourorder: "How is your order?",
  youroverallrating: "Your overall rating",
  adddetailedreview: "Add Detailed review",
  submit: "Submit",
  noorderfound: "No Order Data Found",
  goback: "Go Back",
  orderdetails: "Order Details",
  expecteddeliverydate: "Expected Delivery Date",
  trackingid: "Tracking ID",
  date3sep23: "03 Sep 2023",
  trackingidnumber: "TRK452126542",
  orderstatus: "Order Status",
  orderplaced: "Order Placed",
  datetime: "23 Aug 2023, 04:25 PM",
  datetime2: "23 Aug 2023, 03:54 PM",
  datetime3: "Expected 02 Sep 2023",
  datetime4: "23 Aug 2023, 2023",
  inprogress: "In Progress",
  shipped: "Shipped",
  delivered: "Delivered",
  selectmedia: "Select Media",
  chooseoption: "Choose an option",
  capturephoto: "📸 Capture Photo/Video",
  pickfromgallery: "🖼️ Pick from Gallery",
  cancels: "❌ Cancel",
  jeans: "Jeans",
  shoes: "Shoes",
  hat: "Hat",
  socks: "Socks",
  sweater: "Sweater",
  shorts: "Shorts",
  skirt: "Skirt",
  addphoto: "add Photo",
  nomatchingitem: "No matching item found.",
  errorpickingmedia: "Error picking media:",
  invalidpromocode: "Invalid promo code",
  profilecompleted: "Profile completed successfully",
  pleaseselectgender: "Please select a gender",
  enteravalidnumber: "Enter a valid 10-digit phone number",
  fiftyoff: "50% OFF",
  upto12offcashback: "Up to $12.00 Cashback",
  get50offcombo: "Get 50% OFF for Combo",
  getflat100off: "GEt Flat 100% OFF on Total Amount",
  get500offflat: "Get 500% Flat Discount",
  get100offfull: "Get 100% OFF and Take it for free Only for new Registered User",
  appliedfilter: "Applied Filters: ",
  error: "Error",
  orderdatanotfound: "Order data not found",
  mediaselected: "Media selected:",
  username: "Angie Brekke",
  online: "Online",
  today: "TODAY",
  time804: "08:04 pm",
  messageText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  typemessagehere: "Type a message here...",
  audiotime: "0:13",
  hiddenText: "**** **** **** ****",
  male: "Male",
  female: "Female",
  selectlocation: "Select Location",
  enterhere: "Enter here...",
  comingsoon: 'Coming Soon',
  profile: "ProfileScreen",
  profilename: "Profile Name",
  Settings: "Settings",
  passwordmanager: "Password Manager",
  currentpassword: "Current Password",
  confirmnewpassword: "Confirm New Password",
  passwordMismatch: "Password Mismatch",
  helpcenter: "Help Center",
  privacypolicy: "Privacy Policy",
  cancellationpolicy: "Cancellation Policy",
  loremPara: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus incidunt, rem in quibusdam ut, odit fugit reprehenderit pariatur quae est ipsam! Ea ducimus repudiandae natus vitae. Enim dolorum eum consequuntur.",
  termsconditions: "Terms & Condition",
  loremsmallpara: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus incidunt, rem in quibusdam ut",
  invitefriends: "Invite Friends",
  yeslogout: "Yes, Logout",
  surelogout: "Are you sure you want to log out?",
  modallogout: "Logout",
  logout: "Log out",
  paymentMethods: "Payment Methods",
  avatar1: "Carla Schoen",
  avatar2: "Ester Howard",
  avatar3: "Robert Fox",
  avatar4: "Jacob Jones",
  avatar5: "Darlene Robertson",
  avatar6: "Raplh Edwards",
  avatar7: "Ronald Richards",
  avatar8: "Courtney Harry",
  avatar9: "Vivian Richards",
  avatar10: "Brad Pitt",
  invite: "Invite",
  number1: "207.555.0119",
  number2: "702.555.0122",
  number3: "239.555.0108",
  number4: "316.555.0116",
  number5: "629.555.0129",
  number6: "203.555.0106",
  number7: "209.555.0104",
  number8: "213.555.0239",
  number9: "765.555.0176",
  number10: "654.555.0189",
  logoutsuccess: "Logged out successfully",
  logouterror: "Logout error:",
  question1: "Can I track my order\'s delivery status?",
  question2: "Is there a return policy?",
  question3: "Can I save my favorite items for later?",
  question4: "Can I share products with my friends?",
  question5: "How do I contact customer support?",
  question6: "What payment methods are accepted?",
  question7: "How to add review?",
  answer1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  answer2: "Our return policy allows returns within 30 days of purchase with original receipt.",
  answer3: "Yes, you can save items to your wishlist by clicking the heart icon.",
  answer4: "Yes, you can share product links via social media or messaging apps.",
  answer5: "You can contact our customer support team via email, phone, or live chat.",
  answer6: "We accept credit cards, debit cards, PayPal, Apple Pay, and Google Pay.",
  answer7: "You can add a review by navigating to the product page and scrolling to the reviews section.",
  contactoption1: "Customer Service",
  contactoption2: "WhatsApp",
  contactoption3: "Website",
  contactoption4: "Facebook",
  contactoption5: "Twitter",
  contactoption6:  "Instagram",
  services: "Services",
  general: "General",
  account: "Account",
  phone: "(480) 555-0103",
}

export const localizedStrings = {
    text: "text",
    placeholderColor: "placeholderColor",
    dark: "dark",
    light: "dark",
    black: "black",
    white: "white",
    auto: "auto",
  }